version: '3.8'

services:
  nginx:
    image: nginx:1.19.10
    container_name: nginx
    restart: unless-stopped
    ports:
    - "80:80"


  php:
    image: php:8.0
    container_name: php8
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    volumes:
    - dbfile:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wundersoft


volumes:
  dbfile:

