version: '3.8'

services:
  nginx:
    image: nginx:1.19.10
    container_name: nginx
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./:/var/app
    - ./configs/nginx:/etc/nginx/conf.d


  php:
    image: php:8.0-fpm
    container_name: php8
    restart: unless-stopped
    volumes:
    - ./:/var/app
